resolution: "100"
split: 0
denominator: "microsoft_v7_residential_volume"
features:
  # - "microsoft_v7_residential_volume_250m"
  # - "microsoft_v7_residential_volume_500m"
  # - "microsoft_v7_residential_volume_1000m"
  # - "microsoft_v7_residential_volume_2500m"
  # - "microsoft_v7_residential_volume_5000m"
  # - "microsoft_v7_residential_volume_10000m"
training_target: "admin_log_occupancy_rate"
loss_target: "admin_log_occupancy_rate"
loss_metric: "mse"
test_target: "admin_log_occupancy_rate"
evaluation_target: "admin_log_occupancy_rate"
evaluation_metric: "mse"
random_seed: 112358
mtype: "linear"
optimizer: "adam"
learning_rate: 0.001
num_cores: 8
progress_bar: "true"
